language: cpp

compiler:
  - gcc

jobs:
  include:
  - name: "Vanilla Ubuntu 20.04, no Gromacs and Babel"
    dist: focal
    env:
    - CMAKE_D_OPTIONS="-DWITH_OPENBABEL=OFF -DWITH_GROMACS=OFF"

  - name: "Ubuntu 20.04, preinstalled dependencies"
    dist: focal    
    env:
    - INSTALL_LIST="libeigen3-dev libspdlog-dev pybind11-dev" 
      CMAKE_D_OPTIONS="-DWITH_OPENBABEL=OFF -DWITH_GROMACS=OFF"

before_install:
  - sudo apt-get -y install ${INSTALL_LIST} 

script:
 - mkdir build && cd build
# - docker run --user $(id -u):$(id -g) --rm -v ${TRAVIS_BUILD_DIR}:/workdir:rw ${DOCKER_IMG} /bin/bash -c "cd build && ${CMAKE_BIN} -DWITH_PYTHON=${WITH_PYTHON} -DWITH_OPENBABEL=OFF -DWITH_GROMACS=OFF .. && make"
 - cmake .. ${CMAKE_D_OPTIONS}
 - make -j2
 - rm -rf build
