language: cpp

compiler:
  - gcc

jobs:
  include:
  - name: "Vanilla Ubuntu 20.04, no Gromacs and Babel"
    dist: focal
    env:
    - WITH_GROMACS=OFF WITH_OPENBABEL=OFF

  - name: "Ubuntu 20.04, preinstalled dependencies"
    dist: focal
    before_install:
    - sudo apt-get -y install libeigen3-dev
    env:
    - WITH_GROMACS=OFF WITH_OPENBABEL=OFF

script:
 - mkdir build && cd build
# - docker run --user $(id -u):$(id -g) --rm -v ${TRAVIS_BUILD_DIR}:/workdir:rw ${DOCKER_IMG} /bin/bash -c "cd build && ${CMAKE_BIN} -DWITH_PYTHON=${WITH_PYTHON} -DWITH_OPENBABEL=OFF -DWITH_GROMACS=OFF .. && make"
 - cmake .. && make -j2
 - rm -rf build
